name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_gcc:
    name: Build (GCC)
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        build_type: [Debug, Release]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build g++
      
      - name: Configure CMake
        run: cmake -B build-${{ matrix.build_type }}-gcc -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=g++

      - name: Build Project
        run: cmake --build build-${{ matrix.build_type }}-gcc --verbose
      
      - name: Run Tests
        if: matrix.build_type == 'Debug' # Tests only run in Debug Mode
        run: ctest --test-dir build-${{ matrix.build_type }}-gcc # Expands to Debug only
  
  build_clang:
    name: Build (Clang)
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        build_type: [Debug, Release]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang

      - name: Configure CMake
        run: cmake -B build-${{ matrix.build_type }}-clang -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build Project
        run: cmake --build build-${{ matrix.build_type }}-clang --verbose
      
      - name: Run Tests
        if: matrix.build_type == 'Debug' # Tests only run in Debug Mode
        run: ctest --test-dir build-${{ matrix.build_type }}-clang # Expands to Debug only
 